### ISSUE TITLE
I tried using the Tuneables menu in the Yimmenu version to change my RP, but nothing changes. Am I doing something wrong on my end or is it a bug?

### ISSUE THREAD

**Issue by Chromeyyy** [UltimateMenu/UltimateMenu#24]

**Comment by L7NEG** [comment]
sounds like it is script issue I will look into it for a fix ✅

**Comment by L7NEG** [comment]
Fixed

**Comment by Chromeyyy** [comment]
still doesn't work for me on new version of script. i change my rp number, join a new session and nothing changes.

**Comment by Chromeyyy** [comment]
I would also like to add that everything is set to one. It doesnt initially show my level

**Comment by L7NEG** [comment]
> I would also like to add that everything is set to one. It doesnt initially show my level

bro the rp one is just a multiply not a level setter like kiddions modest menu
